# Generated by Django 2.2 on 2020-11-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('exam_date', models.DateField(verbose_name='考试时间')),
                ('exam_name', models.CharField(max_length=256, verbose_name='考试名称')),
                ('remark', models.CharField(max_length=512, verbose_name='考试备注')),
            ],
            options={
                'verbose_name': '考试信息表',
                'verbose_name_plural': '考试信息表',
                'db_table': 'exam_table',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ScoresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('score_num', models.CharField(max_length=64, verbose_name='考号')),
                ('chinese', models.SmallIntegerField(default=-1, help_text='语文', verbose_name='语文')),
                ('math', models.SmallIntegerField(default=-1, help_text='数学', verbose_name='数学')),
                ('english', models.SmallIntegerField(default=-1, help_text='英语', verbose_name='英语')),
                ('physics', models.SmallIntegerField(default=-1, help_text='物理', verbose_name='物理')),
                ('chemistry', models.SmallIntegerField(default=-1, help_text='化学', verbose_name='化学')),
                ('biology', models.SmallIntegerField(default=-1, help_text='生物', verbose_name='生物')),
                ('politics', models.SmallIntegerField(default=-1, help_text='政治', verbose_name='政治')),
                ('history', models.SmallIntegerField(default=-1, help_text='历史', verbose_name='历史')),
                ('geography', models.SmallIntegerField(default=-1, help_text='地理', verbose_name='地理')),
                ('computer', models.SmallIntegerField(default=-1, help_text='计算机', verbose_name='计算机')),
                ('music', models.SmallIntegerField(default=-1, help_text='音乐', verbose_name='音乐')),
                ('art', models.SmallIntegerField(default=-1, help_text='美术', verbose_name='美术')),
                ('pe', models.SmallIntegerField(default=-1, help_text='体育', verbose_name='体育')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.ExamModel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.StudentModel')),
            ],
            options={
                'verbose_name': '成绩信息表',
                'verbose_name_plural': '成绩信息表',
                'db_table': 'scores_table',
                'ordering': ['exam'],
            },
        ),
    ]
