# Generated by Django 2.2 on 2020-11-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresmodel',
            name='sum_score',
            field=models.SmallIntegerField(default=-1, help_text='总分', verbose_name='总分'),
        ),
    ]
