# Generated by Django 2.2 on 2020-11-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_scoresmodel_sum_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresmodel',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='排序后索引号'),
        ),
    ]
