# Generated by Django 2.2 on 2020-11-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_scoresmodel_sort_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresmodel',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='排序后的名次'),
        ),
    ]
