# Generated by Django 2.2 on 2020-11-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20201130_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresmodel',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='名次'),
        ),
    ]
