# Generated by Django 2.2 on 2020-11-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('student_grade', models.CharField(max_length=128, verbose_name='年级')),
                ('student_class', models.CharField(max_length=128, verbose_name='班级')),
                ('student_cnt', models.SmallIntegerField(default=-1, verbose_name='班级人数')),
            ],
            options={
                'verbose_name': '班级信息表',
                'verbose_name_plural': '班级信息表',
                'ordering': ['student_grade', 'student_class'],
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='学校名称')),
            ],
            options={
                'verbose_name': '学校信息表',
                'verbose_name_plural': '学校信息表',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('student_uuid', models.CharField(help_text='系统级别的唯一身份', max_length=128, primary_key=True, serialize=False, verbose_name='系统级别的唯一身份')),
                ('student_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('0', '在班'), ('1', '已转班'), ('2', '已转学')], default='0', max_length=16)),
                ('in_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.GradeClassModel')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
                'ordering': ['student_uuid'],
            },
        ),
        migrations.CreateModel(
            name='StudentDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('0', '女'), ('1', '男')], default=0, max_length=16)),
                ('address', models.CharField(max_length=256, verbose_name='家庭地址')),
                ('card_num', models.CharField(max_length=24, verbose_name='身份证号码')),
                ('telephone', models.CharField(max_length=18, verbose_name='电话号码')),
                ('student_uuid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='student.StudentModel')),
            ],
            options={
                'verbose_name': '学生详情表',
                'verbose_name_plural': '学生详情表',
                'ordering': ['student_uuid'],
            },
        ),
    ]
